project_id = "axmjbykoyrwbfxeifbnp"

[functions.edit-headshot]
verify_jwt = false

[functions.chat-admin]
verify_jwt = false

[functions.upload-blog-image]
verify_jwt = false

[functions.og-metadata]
verify_jwt = false
